### ISSUE TITLE
Creación del escenario

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/Shakun#22]
**1. Trabajo previo y fondo:**
- [x] Concept del escenario
- [x] Concept de los props y obstáculos
- [x] Crear fondo con zeppelines islas flotantes. Sería bueno elegir ya el skydome.

**2. Escenarios:**
- [x] Tienda
- [x] Zeppelin grande
- [x] Isla del dragón

**3. Programación y postpro**
- [x] Mecánicas y programación
- [x] Texturizar e iluminación

**Comment by yaigh** [comment]
Vamos a empezar a montar los escenarios. Estamos pensando en importar todos los modelados a Unity y en Unity montar los escenarios, hacer prefabs de los objetos e ir colocándolos todos en la escena, o podemos montar el escenario completo en maya y después pasarlo a Unity.

 Álvaro, ¿Dónde crees que mejor montar el escenario?

**Comment by LauFranky** [comment]
No recordaba que teníamos este issue para los escenarios. Muevo las cosas que subimos en el de Modelado a este para organizarnos mejor.

**Comment by LauFranky** [comment]
Anoche encontré un montón de cosas que podemos usar. Props con estilo steampunk, basemesh models para simplemente vestirlos y tener ya a nuestros personajes, perros y aves para las criaturas... 
Me las estoy descargando todas y luego haré por aquí una lista de las cosas que tenemos.

Por otra parte, encontré dos **HDRIs** bastante interesantes **para usar como fondo**. Me he descargado los dos, dejo por aquí un par de capturas de cómo se ven:

![Captura](https://user-images.githubusercontent.com/90465415/147878265-8235233e-046d-41ee-b814-4861b1ec2734.JPG)

![Captura1](https://user-images.githubusercontent.com/90465415/147878267-4ad088b8-f5cc-4b8d-a07a-0316e6b43239.JPG)

**Comment by LauFranky** [comment]
Lista de modelados gratuitos que he encontrado:

**Para el fondo**
Aparte de los HDRIs que enseñé por aquí tenemos varios modelos de zepelines, de nubes y encontré islas flotantes. Dejo por aquí el enlace de descarga, hay islas de diferentes formas para darle variedad:

- https://www.cgtrader.com/3d-models/exterior/cityscape/floating-mountain-over-sci-fi-city-base
- https://www.cgtrader.com/3d-models/various/various-models/floating-mountain-rocks
**¡¡Todo lo del fondo ya estaría solucionado con estos elementos!! :D**

**Escenarios**

- Encontré esta maravilla de mazmorra que nos puede servir para el **interior de la entrada** del inicio del nivel. Cambiaré y añadiré props para darle más estilo steampunk (con los objetos que pondré a continuación) y con un texturizado diferente podemos cambiarle el aspecto a nuestro gusto fácilmente:
Dungeon Low Poly_Model.zip
Dungeon Low Poly_Textures.zip

- También encontré una especie de bunker que sin techo y quitandole algunas paredes podemos hacer que sea el escenario del **zeppelin grande** ya que tiene bastantes habitaciones separadas, escaleras y demás que podemos montar y llenar de props.
(No me deja subir el archivo, asi que dejo el enlace de descarga):
https://www.cgtrader.com/free-3d-models/interior/other/soviet-bunker-kit
Esta plataforma nos puede servir también (dejo enlace de descarga):
https://www.cgtrader.com/items/138285/download-page

- El último escenario (la pequeña **isla flotante donde tienen al dragón**), sería un terreno llano con hierba creada con sistemas de particulas de Blender, y le pondríamos:
Este altar:
https://www.cgtrader.com/free-3d-models/exterior/historic/altar-ruins
Esta jaula grande donde estaría el dragón:
https://www.cgtrader.com/free-3d-print-models/gadgets/office/pen-holder-db7f7ab3-ee22-4345-9d61-89d55a7546a0
Y cadenas:
https://www.cgtrader.com/free-3d-models/various/various-models/chain-fcccc622-f7ab-41e7-a909-3f9f1b57a261

**Comment by LauFranky** [comment]
**Props**

Espada del boss 
https://www.cgtrader.com/free-3d-models/military/melee/steampunk-sword-dabc7480-878a-4fbf-9c56-923797db382f
Cofre
https://www.cgtrader.com/free-3d-models/furniture/other/fantasy-chest-1dd95585-f1b4-4236-bad5-9ebd5edad3dd
Barandilla
https://www.cgtrader.com/free-3d-models/interior/other/classic-handrail
Columna hueca para los fuegos del zeppelin
https://www.cgtrader.com/free-3d-models/furniture/table/eichholtz-column-niagora
Columna pared decorada
https://www.cgtrader.com/free-3d-models/interior/other/classic-decoration-column


- Decorados varios:

Engranajes
https://www.cgtrader.com/free-3d-print-models/gadgets/office/steampunk-cog-collection-print-ready
Experimento
https://www.cgtrader.com/free-3d-models/electronics/other/egevgergvd
Teléfono
https://www.cgtrader.com/free-3d-models/interior/other/stea-a2473819-2d65-41ef-b4b6-6f64c335b310
Cámara
https://www.cgtrader.com/free-3d-models/electronics/video/steampunk-camera-12b5d11b-fe3b-4fee-8d8b-b3b4ecde9c09
Reloj grande
https://www.cgtrader.com/free-3d-models/household/other/grandfather-clock-34e6b25e-86d7-429a-b47f-0fd4bd05b45e
Maletín
https://www.cgtrader.com/free-3d-models/household/other/vintage-suitcase-528ee5e8-4a33-4e50-a8aa-aac7267d1b78
Globo terráqueo
https://www.cgtrader.com/free-3d-models/interior/living-room/old-antique-standing-globe-pbr
Radio
https://www.cgtrader.com/free-3d-models/electronics/audio/old-radio-6e118b1b-067f-4b2d-9c0c-dc8f344f3829
Lámpara de velas clásica
https://www.cgtrader.com/free-3d-models/furniture/lamp/chandelier-classical

- Obstáculos del escenario

https://www.cgtrader.com/free-3d-models/electronics/computer/usb-drive-steampunk-2015
Nave vieja
https://www.cgtrader.com/free-3d-models/aircraft/other/air-mobile-by-art-vincent-bryant
Bomba de agua
https://www.cgtrader.com/free-3d-models/exterior/sci-fi/3d-prop-model
Props de mazmorra
https://www.cgtrader.com/free-3d-models/exterior/other/wood-metal-trim-sheet-asset-pack
https://www.cgtrader.com/free-3d-models/interior/kitchen/interior-objects
Muebles vintage
https://www.cgtrader.com/free-3d-models/furniture/furniture-set/furniture-free-pack
Carretilla madera
https://www.cgtrader.com/free-3d-models/furniture/cabinet/furniture-vintage-1
Caldera
https://www.cgtrader.com/free-3d-models/furniture/appliance/vintage-boiler
